services:
  api_host: "localhost"
  api_base_path: "/nomad-oasis"

oasis:
  is_oasis: true
  uses_central_user_management: true

plugins:
  entry_points:
    include:
      # Nomad Material Processing
      # - "nomad_material_processing:schema"
      # - "nomad_material_processing.vapor_deposition:schema"
      # - "nomad_material_processing.vapor_deposition.pvd:sputtering_schema"
      # - "nomad_material_processing.vapor_deposition.cvd:schema"
      # - "nomad_material_processing.vapor_deposition.pvd:mbe_schema"
      # - "nomad_material_processing.vapor_deposition.pvd:pld_schema"
      # - "nomad_material_processing.vapor_deposition.pvd:schema"
      # - "nomad_material_processing.vapor_deposition.pvd:sputtering_schema"
      # - "nomad_material_processing.vapor_deposition.pvd:thermal_schema"
      # - "nomad_material_processing.solution:schema"
    exclude:
      # ...
      

north:
  jupyterhub_crypt_key: "978bfb2e13a8448a253c629d8dd84ff89587f30e635b753153960930cad9d36d"
  tools:
    options:
      jupyter:
        image: ghcr.io/fabianschoeppach/nomad-unitov-image/jupyter:main

meta:
  deployment: "oasis"
  deployment_url: "https://my-oasis.org/api"
  maintainer_email: "me@my-oasis.org"

logstash:
  enable: false

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1
